### ISSUE TITLE
Fix Prevent kernel upgrades

### ISSUE THREAD

**Issue by Bassinator** [einfachIT/epicPiOS#30]
holding back kernel to prevent kernel upgrades seems not to work

TASK [Hold raspberrypi-kernel] *************************************************
skipping: [epic-docker-host]

preventing kernel upgrade is needed. Otherwise this will break the reset capability:

- if kernel is upgrade, boot and root of the recovery partition are out of sync. 
- can also be fixed by doing upgrades to both partitions at the same time (chroot to recovery partition)

**Comment by Bassinator** [comment]
As a workaround, this can be handled by holding pack the specific packages.
e.g. with ansible in bullseye:
```
    - name: Hold raspberrypi-kernel for bullseye
      dpkg_selections:
        name: raspberrypi-kernel
        selection: hold
      when: "'raspberrypi-kernel' in ansible_facts.packages"
```
or with ansible in bookworm:
```
    - name: Hold raspberrypi-kernel for bookworm
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ ansible_facts.packages | select('match', 'linux-image-rpi*' ) }}"
```
